<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf772c8e14ea0e9cca1a7c600008cbbb7
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wilder\\ComposerQuest\\App\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wilder\\ComposerQuest\\App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf772c8e14ea0e9cca1a7c600008cbbb7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf772c8e14ea0e9cca1a7c600008cbbb7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf772c8e14ea0e9cca1a7c600008cbbb7::$classMap;

        }, null, ClassLoader::class);
    }
}
